load("@rules_ruby//ruby:defs.bzl", "rb_library")
load("//rb/spec:tests.bzl", "rb_integration_test")

rb_library(
    name = "spec_helper",
    testonly = True,
    srcs = [
        "spec_helper.rb",
        "spec_support.rb",
    ] + glob(["spec_support/**/*"]),
    data = [
        "//rb:manager-linux",
        "//rb:manager-macos",
        "//rb:manager-windows",
    ],
    visibility = ["//rb/spec:__subpackages__"],
    deps = [
        "//rb/lib:selenium-webdriver",
        "//rb/lib/selenium:devtools",
        "//rb/lib/selenium:server",
        "//rb/lib/selenium:webdriver",
        "//rb/lib/selenium/webdriver:atoms",
        "//rb/lib/selenium/webdriver:common",
        "//rb/lib/selenium/webdriver:remote",
        "//rb/spec:rspec_matchers",
        "@bundle",
    ],
)

_OS_SENSITIVE_TESTS = [
    "action_builder_spec.rb",
    "takes_screenshot_spec.rb",
    "window_spec.rb",
]

_BIDI_TESTS = [
    "bidi_spec.rb",
    "navigation_spec.rb",
    "network_spec.rb",
]

_DEVTOOLS_TESTS = ["devtools_spec.rb"]

[
    rb_integration_test(
        name = file[:-8],
        srcs = [file],
        deps = [
            "//rb/lib/selenium/webdriver:common",
        ],
    )
    for file in glob(
        ["*_spec.rb"],
        exclude = _OS_SENSITIVE_TESTS + _BIDI_TESTS + _DEVTOOLS_TESTS,
    )
]

[
    rb_integration_test(
        name = f[:-8],
        srcs = [f],
        tags = ["os-sensitive"],
        deps = [
            "//rb/lib/selenium/webdriver:common",
        ],
    )
    for f in _OS_SENSITIVE_TESTS
]

[
    rb_integration_test(
        name = f[:-8],
        srcs = [f],
        tags = ["bidi"],
        deps = [
            "//rb/lib/selenium/webdriver:bidi",
        ],
    )
    for f in _BIDI_TESTS
]

[
    rb_integration_test(
        name = f[:-8],
        srcs = [f],
        tags = ["exclusive-if-local"],
        deps = [
            "//rb/lib/selenium/devtools",
        ],
    )
    for f in _DEVTOOLS_TESTS
]
